import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header'
import { Stack } from '@chakra-ui/react'
import CompanyDetail from '../components/Homepage/CompanyDetail'
import Footer from '../components/Footer/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wifibase - Your best wifi service provider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stack>
        <Header />
        <CompanyDetail />
      </Stack>
      <Footer />
    </div>
  )
}
